name: simprokcore
description: A template that removes all headache of designing your application's architecture by providing a simple API that encourages you to separate an application's logic properly.
version: 1.1.7
homepage: https://github.com/simprok-dev/simprokcore-flutter
documentation: https://github.com/simprok-dev/simprokcore-flutter/wiki

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  simprokmachine: ^1.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
